version: '3.8'

services:
  melquisapi:
    container_name: melquis--api
    build: ./
    command: gunicorn --bind 0.0.0.0:8000 manage:app
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - app__network
    restart: unless-stopped

networks:
  app__network:
    driver: bridge
